### ISSUE TITLE
RuntimeError: CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by mikalyoung** [jacobgil/pytorch-pruning#1]
What could be the cause and fix of this CUDNN_STATUS_BAD_PARAM error?  I cannot get this to extract the features.  Pytorch otherwise runs fine on my Ubuntu + Anaconda machine.   

>my@my:~/Dropbox/x/CV/pytorch-pruning$ CUDA_VISIBLE_DEVICES=0 python finetune_original.py --train
Downloading: "https://download.pytorch.org/models/vgg16-397923af.pth" to /home/my/.torch/models/vgg16-397923af.pth
100%|553433881/553433881 [08:01<00:00, 1148236.75it/s]
Epoch:  0
Traceback (most recent call last):
  File "finetune.py", line 268, in <module>
    if args.train:
  File "finetune.py", line 163, in train
    print "Epoch: ", i
  File "finetune.py", line 181, in train_epoch
    for batch, label in self.train_data_loader:
  File "finetune.py", line 176, in train_batch
    else:
  File "/home/my/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "finetune.py", line 40, in forward
    def forward(self, x):
  File "/home/my/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/my/anaconda2/lib/python2.7/site-packages/torch/nn/modules/container.py", line 64, in forward
    input = module(input)
  File "/home/my/anaconda2/lib/python2.7/site-packages/torch/nn/modules/module.py", line 206, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/my/anaconda2/lib/python2.7/site-packages/torch/nn/modules/conv.py", line 237, in forward
    self.padding, self.dilation, self.groups)
  File "/home/my/anaconda2/lib/python2.7/site-packages/torch/nn/functional.py", line 40, in conv2d
    return f(input, weight, bias)
RuntimeError: CUDNN_STATUS_BAD_PARAM

**Comment by jacobgil** [comment]
Still relevant?
Try printing x.size() in forward. It should be [batch_size, 3, height, width]

**Comment by ashupednekar** [comment]
Same issue here... for batch_size upto 16 it's giving this error, beyond 16 results in CUDA out of memory.
