### ISSUE TITLE
Out of memory,when I pruned model test

### ISSUE THREAD

**Issue by Tianxiaomo** [jacobgil/pytorch-pruning#19]
I use Tesla k80 -12G *4,When I prunning the training test everything was normal, but after the pruned test memory overflow.
THCudaCheck FAIL file=/pytorch/aten/src/THC/generic/THCStorage.cu line=58 error=2 : out of memory
Traceback (most recent call last):
  File "/home/b418-xiwei/.pycharm_helpers/pydev/pydevd.py", line 1664, in <module>
    main()
  File "/home/b418-xiwei/.pycharm_helpers/pydev/pydevd.py", line 1658, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/b418-xiwei/.pycharm_helpers/pydev/pydevd.py", line 1068, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/home/b418-xiwei/.pycharm_helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/b418-xiwei/hgh/prune/finetune.py", line 343, in <module>
    fine_tuner.prune()
  File "/home/b418-xiwei/hgh/prune/finetune.py", line 267, in prune
    self.test()
  File "/home/b418-xiwei/hgh/prune/finetune.py", line 187, in test
    output = model(Variable(batch))
  File "/home/b418-xiwei/anaconda3/envs/distiller/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/b418-xiwei/hgh/prune/finetune.py", line 68, in forward
    x = self.features(x)
  File "/home/b418-xiwei/anaconda3/envs/distiller/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/b418-xiwei/anaconda3/envs/distiller/lib/python3.6/site-packages/torch/nn/modules/container.py", line 91, in forward
    input = module(input)
  File "/home/b418-xiwei/anaconda3/envs/distiller/lib/python3.6/site-packages/torch/nn/modules/module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/b418-xiwei/anaconda3/envs/distiller/lib/python3.6/site-packages/torch/nn/modules/pooling.py", line 142, in forward
    self.return_indices)
  File "/home/b418-xiwei/anaconda3/envs/distiller/lib/python3.6/site-packages/torch/nn/functional.py", line 360, in max_pool2d
    ret = torch._C._nn.max_pool2d(input, kernel_size, stride, padding, dilation, ceil_mode)
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58

I use batch_size=16,so it is

**Comment by cc94226** [comment]
What GPU are you using?

**Comment by CodePlay2016** [comment]
have you solve this problem? I found that in finetune.py line172 and line174, this two backward operation will cause doubling the memory usage twice, increasing my memory from 3200MB to 7000MB than to 11000MB. The first increment is used when getting the pruning plan, so the gradient calculated is useless when finetuning, but I haven't found any way to clear that gradient cache.

**Comment by weixia-cs** [comment]
@Tianxiaomo hi， can you tell me the command of test model，i can‘t find it，thy.

**Comment by promach** [comment]
@CodePlay2016 I am facing the almost similar [out-of-memory problem](https://github.com/jacobgil/pytorch-pruning/issues/6#issuecomment-427620701)

Could you comment about this ? Do you have any countermeasure so far ?
